language: go

go:
  - 1.12.x

cache: yarn

git:
  depth: 1

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - export PATH=$PATH:$GOROOT/bin
  - export GOPATH=$TRAVIS_BUILD_DIR

before_script:
  - yarn
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin vX.Y.Z
  - golangci-lint --version

script:
  - golangci-lint run ./...
  - make test
  - make build
