language: go

go:
  - 1.12.x

cache: yarn

git:
  depth: 1

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

before_script:
  - yarn
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run src/background/
  - make test
  - make build
