language: go

go:
  - 1.12.x

cache: yarn

git:
  depth: 1

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

before_script:
  - yarn
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - GOOS=js GOARCH=wasm go test -v -exec="$(GOROOT)/misc/wasm/go_js_wasm_exec" ./...
  - yarn webpack
  - GOOS=js GOARCH=wasm go build -o main.wasm clipgo/src/background
  - mv main.wasm build && cp src/manifest.json src/icons/*.png build
