version: 2
jobs:
  build:
    docker:
      - image: circleci/go:latest
      - image: circleci/node:latest
    working_directory: /home/circleci/go/src/github.com/ramenjuniti/clipgo
    steps:
      - checkout
      - run: make install
      - run: make test
      - run: make build
