version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
      - image: circleci/node:10
    working_directory: /home/circleci/go/src/github.com/ramenjuniti/clipgo
    steps:
      - checkout
      - run: npm install --global yarn
      - run: make install
      - run: make test
      - run: make build
