version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12-node
    working_directory: /home/circleci/go/src/github.com/ramenjuniti/clipgo
    steps:
      - checkout
      - run: export PATH=$GOROOT/bin:$PATH
      - run:
          name: install
          command: |
            make install
      - run:
          name: test
          command: |
            make test
      - run:
          name: build
          command: |
            make build
